### ISSUE TITLE
DoD file submission only accepts utf-8 encoded files

### ISSUE THREAD

**Issue by mckibbenc** [fireeye/fireeye-python#2]
You can't submit PDF, PNG, or other non utf-8 encoded files.  Need to support all filetypes.  Here is the error I received when trying to submit a PNG file:

>>> response = detection.submit_file(files={"file": ('filename', open('./fireeyelogo-vector.png', 'r'))})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fireeyepy/__init__.py", line 75, in submit_file
    return self.post(self.api_host, "/files", body, files)
  File "/usr/local/lib/python3.7/site-packages/fireeyepy/__init__.py", line 108, in post
    return self.parse(host, self.session.post(uri, data=data, files=files, headers=headers))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 504, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by mckibbenc** [comment]
I solved the issue.  The docs for the client library use the read mode 'r' which attempts to read files as text instead of binary.  As a result, non text files, like images, cause an error when opening the file.  By using the binary mode 'rb', any file can be read and submitted to the DoD API.  I'm going to submit a PR to update the README to use 'rb' instead of just 'r' in the file submission example.
